en = {
    "option_back_EN": "⏎ Return",
    "option_default_EN": "➤ Default",
    "option_next_EN": "➔ Continue",
    "option_cancel_EN": "⊠ Cancel",
    "option_back_to_main_menu_EN": "⏎ Return to the Main Menu",
    "option_video_source_EN": "Use a video file to extract images",
    "option_web_source_EN": "Use a web page to extract images",
    "message_url_project_EN": "Enter the URL of the web page.",
    "message_name_project_EN": "Type a name for the project",
    "value_seconds_video_EN": "The value must be between 1 and 1800 seconds (1 to 30 minutes).",
    "message_integer_value_EN": "The value must be an integer.",
    "option_welcome_EN": "Welcome menu.",
    "option_new_project_EN": "New Project.",
    "option_automatic_next_EN": "➤ Continue",
    "option_menu_session_screen_EN": "Go to the Screen Session menu",
    "title_menu_session_screen_EN": "Screen Session Menu",
    "help_menu_session_screen_EN": "Creating a new screen capture session allows you to isolate new captures, making it easier to adjust settings and observe changes.",
    "ask_create_new_session_screen_EN": "Start a new screen session",
    "ask_select_a_session_screen_EN": "Switch to an existing Screen Session",
    "ask_delete_a_session_screen_EN": "Delete a Screen Session",
    "message_new_session_created_EN": "A new Screen Session has been created: *screen_id",
    "option_existing_project_EN": "Continue with an Existing Project.",
    "option_save_config_EN": "Do you want to save the changes?",
    "message_to_continue_EN": "To continue select an option.",
    "option_start_trigger_image_EN": "Continue with the start session image",
    "option_end_trigger_image_EN": "Continue with the end session image",
    "option_list_trigger_image_EN": "Continue adding more images for capture activation.",
    "option_interest_trigger_area_EN": "Continue defining the Session Indicators and Capture area.",
    "option_comparison_area_EN": "Continue defining the area for change detection.",
    "option_hsv_color_area_EN": "Change the color to indicate an area.",
    "option_percent_start_trigger_EN": "Change minimum similarity threshold. The current value is *threshold",
    "option_percent_end_trigger_EN": "Change minimum similarity threshold. End of session. The current value is *threshold",
    "option_percent_list_trigger_EN": "Change minimum similarity threshold. The current value is *threshold",
    "option_percent_comparison_area_EN": "Change minimum difference threshold. The current value is *threshold",
    
    "title_percent_start_trigger_EN": "Minimum Similarity Threshold. Login Trigger",
    "help_percent_start_trigger_EN": "Represents the minimum similarity threshold required to consider a match with the established login image. A value of 100% means that the image must be completely identical to be considered a login.",
    "ask_percent_start_trigger_EN": "Enter a value between 1 and 100%",
    
    
    "title_percent_end_trigger_EN": "Minimum Similarity Threshold. Logout Trigger",
    "help_percent_end_trigger_EN": "Represents the minimum similarity threshold required to consider a match with the established logout image. A value of 100% means that the image must be completely identical to be considered a logout.",
    "ask_percent_end_trigger_EN": "Enter a value between 1 and 100%",
    
    "title_percent_list_trigger_EN": "Minimum Similarity Threshold. Capture Reference Images",
    "help_percent_list_trigger_EN": "Defines the minimum similarity threshold required to consider a match with the reference image for capture. A value of 100% means that the image must be completely identical to be considered a valid capture.",
    "ask_percent_list_trigger_EN": "Enter a value between 1 and 100%",

    "title_percent_comparison_area_EN": "Comparison Area Threshold",
    "help_percent_comparison_area_EN": "If set to 100%, the image must be completely different from the previous image to be considered changed. In other words, the percentage of difference between the two images must reach 100% for a significant change to be detected. A 100% threshold means a change will only be detected if all pixels have varied.",
    "ask_percent_comparison_area_EN": "Enter a value between 1 and 100%",
    
    "option_show_panel_project_EN": "⏎ Return to the Main Menu",
    "option_select_language_EN": "Change Language.",
    "message_select_language_EN": "Select a language from the available options.",
    "option_init_main_process_EN": "Start the main capture process",
    "option_stop_EN": "⊠ Close.",
    "option_menu_first_recording_EN": "Continue with the screen recording.",
    "option_menu_recording_EN": "Create a new screen recording video.",
    "select_project_folder_EN": "Select an project.",
    "question_resolution_EN": "Select the virtual screen resolution to be used throughout the project.",
    "question_seconds_video_EN": "Specify the duration in seconds for which you want to record the screen.",
    "enter_number_option_EN": "Enter the number of the desired option:",
    "select_option_EN": "Select an option: ",
    "invalid_option_EN": "Invalid option. Please try again.",
    "invalid_input_EN": "Invalid input. Please try again.",
    "starting_message_EN": "Starting..",
    "virtual_screen_initialized_EN": "Virtual screen initialized, starting chrome driver url: ",
    "chrome_driver_started_EN": "Chrome driver started, capturing screenshot ...",
    "recording_started_EN": "Recording started",
    "recording_finished_EN": "Recording finished",
    "duration_seconds_EN": "Duration in seconds: ",
    "screen_resolution_EN": "Screen Resolution: ",
    "saving_video_EN": "Saving video ... in: ",
    "video_saved_EN": "Video saved in: ",

}

es = {
    "option_back_ES": "⏎ Regresar",
    "option_default_ES": "➤ Por Defecto",
    "option_next_ES": "➔ Continuar",
    "option_cancel_ES": "⊠ Cancelar",
    "option_back_to_main_menu_ES": "⏎ Regresar al Menú Principal",
    "option_video_source_ES": "Utilizar un archivo de video para extraer las imágenes",
    "option_web_source_ES": "Utilizar una página web para extraer las imágenes",
    "message_url_project_ES": "Introduce la URL de la página web.",
    "message_name_project_ES": "Escribe un nombre para el proyecto",
    "value_seconds_video_ES": "El valor debe estar entre 1 y 1800 segundos (de 1 a 30 minutos).",
    "message_integer_value_ES": "El valor debe ser un entero.",
    "option_welcome_ES": "Menú de bienvenida.",
    "option_new_project_ES": "Nuevo Proyecto.",
    "option_automatic_next_ES": "➤ Continuar",
    "option_menu_session_screen_ES": "Ir al menú de Sesión de Pantallas",
    "title_menu_session_screen_ES": "Menú de Sesión de Pantalla",
    "help_menu_session_screen_ES": "Crear una nueva sesión pantalla de capturas permite aislar nuevas capturas, lo que facilita realizar ajustes en la configuración y observar los cambios.",
    "ask_create_new_session_screen_ES": "Iniciar una nueva sesión de pantalla",
    "ask_select_a_session_screen_ES": "Cambiar a una Sesión de Pantalla existente",
    "ask_delete_a_session_screen_ES": "Eliminar una Sesión de Pantalla",
    "message_new_session_created_ES": "Se ha Creado una nueva Sesión de Pantalla: *screen_id",
    "option_existing_project_ES": "Continuar con un Proyecto Existente.",
    "option_save_config_ES": "¿Desea guardar los cambios?",
    "message_to_continue_ES": "Para continuar seleccione una opción",
    "option_start_trigger_image_ES": "Continuar con la imagen de inicio de sesión",
    "option_end_trigger_image_ES": "Continuar con la imagen de fin de sesión",
    "option_list_trigger_image_ES": "Continuar añadiendo más imágenes para la activación de las capturas.",
    "option_interest_trigger_area_ES": "Continuar con la definición del área de Indicadores de Sesión y Captura.",
    "option_comparison_area_ES": "Continuar con la definición del área para la detección de cambios.",
    "option_hsv_color_area_ES": "Cambiar el color para indicar un área.",
    "title_percent_start_trigger_ES": "Umbral de similitud mínima. Inicio de sesión",
    "help_percent_start_trigger_ES": "Representa el umbral mínimo de similitud necesario para considerar una coincidencia con la imagen de inicio de sesión establecida. Un valor del 100% indica que la imagen debe ser totalmente idéntica para que se considere el inicio de sesión.",
    "ask_percent_start_trigger_ES": "Introduzca un valor entre 1 y 100%",
    "option_percent_start_trigger_ES": "Cambiar umbral de similitud mínima, el valor actual *threshold",
    "option_percent_end_trigger_ES": "Cambiar umbral de similitud mínima. Fin de sesión, el valor actual *threshold",
    "option_percent_list_trigger_ES": "Cambiar umbral de similitud mínima, el valor actual *threshold",
    "option_percent_comparison_area_ES": "Cambiar umbral de diferencia mínima, el valor actual *threshold",
    "title_percent_end_trigger_ES": "Umbral de similitud mínima. Fin de sesión",
    "help_percent_end_trigger_ES": "Representa el umbral mínimo de similitud necesario para considerar una coincidencia con la imagen de fin de sesión establecida. Un valor del 100% indica que la imagen debe ser totalmente idéntica para que se considere el fin de sesión.",
    "ask_percent_end_trigger_ES": "Introduzca un valor entre 1 y 100%",
    "title_percent_list_trigger_ES": "Umbral de similitud mínima. Referencia de Captura",
    "help_percent_list_trigger_ES": "Define el umbral mínimo de similitud necesario para considerar una coincidencia con la imagen de referencia para la captura. Un valor del 100% indica que la imagen debe ser totalmente idéntica para considerarse una captura válida.",
    "ask_percent_list_trigger_ES": "Introduzca un valor entre 1 y 100%",
    "title_percent_comparison_area_ES": "Umbral de comparación de área",
    "help_percent_comparison_area_ES": "Si se establece en 100%, la imagen debe ser completamente diferente de la imagen anterior para que se considere un cambio. En otras palabras, el porcentaje de diferencia entre las dos imágenes debe alcanzar el 100% para que se detecte un cambio significativo. Un umbral del 100% significa que un cambio solo se detectará si todos los píxeles han variado.",
    "ask_percent_comparison_area_ES": "Introduzca un valor entre 1 y 100%",
    "option_show_panel_project_ES": "⏎ Regresar al Menú Principal",
    "option_select_language_ES": "Cambiar Idioma",
    "message_select_language_ES": "Seleccione un idioma de las opciones disponibles.",
    "option_init_main_process_ES": "Iniciar el proceso principal de captura",
    "option_stop_ES": "⊠ Cerrar.",
    "option_menu_first_recording_ES": "Continuar con la grabación de pantalla.",
    "option_menu_recording_ES": "Crear un nuevo video de grabación de pantalla.",
    "select_project_folder_ES": "Seleccionar un proyecto.",
    "question_resolution_ES": "Seleccionar la resolución de pantalla virtual que se utilizará en todo el proyecto.",
    "question_seconds_video_ES": "Especificar la duración en segundos durante la cual desea grabar la pantalla.",
    "enter_number_option_ES": "Introduzca el número de la opción deseada:",
    "select_option_ES": "Seleccione una opción: ",
    "invalid_option_ES": "Opción no válida. Inténtalo de nuevo.",
    "invalid_input_ES": "Entrada no válida. Inténtalo de nuevo.",
    "starting_message_ES": "Iniciando..",
    "virtual_screen_initialized_ES": "Pantalla virtual inicializada, iniciando el driver de Chrome en la URL: ",
    "chrome_driver_started_ES": "Driver de Chrome iniciado, capturando captura de pantalla ...",  
    "recording_started_ES": "Grabación iniciada",
    "recording_finished_ES": "Grabación finalizada",
    "duration_seconds_ES": "Duración en segundos: ",
    "screen_resolution_ES": "Resolución de pantalla: ",
    "saving_video_ES": "Guardando video ... en: ",
    "video_saved_ES": "Video guardado en: ",
    }

pt = {
    "option_back_PT": "⏎ Voltar",
    "option_default_PT": "➤ Padrão",
    "option_next_PT": "➔ Continuar",
    "option_cancel_PT": "⊠ Cancelar",
    "option_back_to_main_menu_PT": "⏎ Voltar ao Menu Principal",
    "option_video_source_PT": "Usar um arquivo de vídeo para extrair imagens",
    "option_web_source_PT": "Usar uma página web para extrair imagens",
    "message_url_project_PT": "Digite a URL da página web.",
    "message_name_project_PT": "Digite um nome para o projeto",
    "value_seconds_video_PT": "O valor deve estar entre 1 e 1800 segundos (1 a 30 minutos).",
    "message_integer_value_PT": "O valor deve ser um número inteiro.",
    "option_welcome_PT": "Menu de Boas-Vindas.",
    "option_new_project_PT": "Novo Projeto.",
    "option_automatic_next_PT": "➤ Continuar",
    "option_menu_session_screen_PT": "Ir para o menu de Sessão de Tela",
    "title_menu_session_screen_PT": "Menu de Sessão de Tela",
    "help_menu_session_screen_PT": "Criar uma nova sessão de captura de tela permite isolar novas capturas, facilitando ajustes nas configurações e observação de mudanças.",
    "ask_create_new_session_screen_PT": "Iniciar uma nova sessão de tela",
    "ask_select_a_session_screen_PT": "Mudar para uma Sessão de Tela existente",
    "ask_delete_a_session_screen_PT": "Excluir uma Sessão de Tela",
    "message_new_session_created_PT": "Uma nova Sessão de Tela foi criada: *screen_id",
    "option_existing_project_PT": "Continuar com um Projeto Existente.",
    "option_save_config_PT": "Deseja salvar as alterações?",
    "message_to_continue_PT": "Para continuar, selecione uma opção.",
    "option_start_trigger_image_PT": "Continuar com a imagem de início de sessão",
    "option_end_trigger_image_PT": "Continuar com a imagem de fim de sessão",
    "option_list_trigger_image_PT": "Continuar adicionando mais imagens para ativação de captura.",
    "option_interest_trigger_area_PT": "Continuar definindo a área de Indicadores de Sessão e Captura.",
    "option_comparison_area_PT": "Continuar definindo a área para detecção de mudanças.",
    "option_hsv_color_area_PT": "Alterar a cor para indicar uma área.",
    "title_percent_start_trigger_PT": "Limiar de Semelhança Mínima. Início de sessão",
    "help_percent_start_trigger_PT": "Representa o limiar mínimo de semelhança necessário para considerar uma correspondência com a imagem de início de sessão estabelecida. Um valor de 100% significa que a imagem deve ser completamente idêntica para ser considerada um início de sessão.",
    "ask_percent_start_trigger_PT": "Digite um valor entre 1 e 100%",
    "option_percent_start_trigger_PT": "Alterar o limiar de semelhança mínima, o valor atual é *threshold",
    "option_percent_end_trigger_PT": "Alterar o limiar de semelhança mínima. Fim de sessão, o valor atual é *threshold",
    "option_percent_list_trigger_PT": "Alterar o limiar de semelhança mínima. O valor atual é *threshold",
    "option_percent_comparison_area_PT": "Alterar o limiar de diferença mínima. O valor atual é *threshold",
    "title_percent_end_trigger_PT": "Limiar de Semelhança Mínima. Fim de sessão",
    "help_percent_end_trigger_PT": "Representa o limiar mínimo de semelhança necessário para considerar uma correspondência com a imagem de fim de sessão estabelecida. Um valor de 100% significa que a imagem deve ser completamente idêntica para ser considerada um fim de sessão.",
    "ask_percent_end_trigger_PT": "Digite um valor entre 1 e 100%",
    "title_percent_list_trigger_PT": "Limiar de Semelhança Mínima. Imagens de Referência",
    "help_percent_list_trigger_PT": "Define o limiar mínimo de semelhança necessário para considerar uma correspondência com a imagem de referência para captura. Um valor de 100% significa que a imagem deve ser completamente idêntica para ser considerada uma captura válida.",
    "ask_percent_list_trigger_PT": "Digite um valor entre 1 e 100%",
    "title_percent_comparison_area_PT": "Limiar de Comparação de Área",
    "help_percent_comparison_area_PT": "Se definido como 100%, a imagem deve ser completamente diferente da imagem anterior para ser considerada uma mudança. Em outras palavras, a porcentagem de diferença entre as duas imagens deve atingir 100% para que uma mudança significativa seja detectada. Um limiar de 100% significa que uma mudança só será detectada se todos os pixels tiverem variado.",
    "ask_percent_comparison_area_PT": "Digite um valor entre 1 e 100%",
    "option_show_panel_project_PT": "⏎ Voltar ao Menu Principal",
    "option_select_language_PT": "Alterar Idioma",
    "message_select_language_PT": "Selecione um idioma das opções disponíveis.",
    "option_init_main_process_PT": "Iniciar o processo principal de captura",
    "option_stop_PT": "⊠ Fechar.",
    "option_menu_first_recording_PT": "Continuar com a gravação de tela.",
    "option_menu_recording_PT": "Criar um novo vídeo de gravação de tela.",
    "select_project_folder_PT": "Selecionar um projeto.",
    "question_resolution_PT": "Selecione a resolução de tela virtual a ser usada em todo o projeto.",
    "question_seconds_video_PT": "Especifique a duração em segundos para a qual deseja gravar a tela.",
    "enter_number_option_PT": "Digite o número da opção desejada:",
    "select_option_PT": "Selecione uma opção: ",
    "invalid_option_PT": "Opção inválida. Tente novamente.",
    "invalid_input_PT": "Entrada inválida. Tente novamente.",
    "starting_message_PT": "Iniciando..",
    "virtual_screen_initialized_PT": "Tela virtual inicializada, iniciando o driver do Chrome na URL: ",
    "chrome_driver_started_PT": "Driver do Chrome iniciado, capturando captura de tela ...",
    "recording_started_PT": "Gravação iniciada",
    "recording_finished_PT": "Gravação concluída",
    "duration_seconds_PT": "Duração em segundos: ",
    "screen_resolution_PT": "Resolução da tela: ",
    "saving_video_PT": "Salvando vídeo ... em: ",
    "video_saved_PT": "Vídeo salvo em: ",
    
    }

map = {}
map.update(en)
map.update(es)
map.update(pt)

if __name__ == "__main__":
    RED = '\033[91m'
    RESET = '\033[0m'

    dict_source= en
    suffix_dict_source = "EN"
    list_dict_to_check = [es, pt]
    suffix_to_check = ["ES", "PT"]
    print(f"total_keys EN: {len(dict_source.keys())}")
    
    for i, dict_lang in enumerate(list_dict_to_check):

        for  key, value in dict_source.items():
            cropped_key = key[:-2]
            suffix = key[-2:]
            if suffix != suffix_dict_source:
                print (f"{RED} The suffix {suffix} is incorret in dict_source key: {key} {RESET}")

            try:
                dict_lang[f"{cropped_key}{suffix_to_check[i]}"]
            except KeyError as e:
                print (f"{RED} This {e} key is not present in {suffix_to_check[i]}{RESET}")
                
        print(f"total_keys {suffix_to_check[i]}: {len(dict_lang.keys())}")
