dict_panel_title_en = {
    "PROJECT_EN": "PROJECT OVERVIEW 🗃️ ",
    "START_SESSION_TRIGGER_IMAGE_EN": "START IMAGE SESSION INDICATOR 🖼️ ",
    "END_SESSION_TRIGGER_IMAGE_EN": "END IMAGE SESSION INDICATOR 🖼️ ",
    "LIST_TRIGGER_IMAGES_EN": "IMAGES OF CAPTURE INDICATORS 🖼️ ",
    "HSV_COLOR_AREA_EN": "COLOR OF AREAS 🟢 ",
    "INTEREST_TRIGGER_AREA_EN": "AREA OF INDICATORS IMAGES 🔲 ",
    "COMPARISON_AREA_EN": "AREA OF COMPARISON 🔲 ",
    # WEB
    "SCREEN_RECORDING_EN": "VIDEO SCREEN RECORDING 📹 ",
    "CAPTURES_EN": "CAPTURE SESSION 📸 ",
    #VIDEO
    "VIDEO_SOURCE_EN": "VIDEO SOURCE 🎞️ ",
    

}

dict_panel_title_es = {
    "PROJECT_ES": "GENERAL DEL PROYECTO 🗃️ ",
    "START_SESSION_TRIGGER_IMAGE_ES": "IMAGEN INDICADORA DE INICIO DE SESIÓN 🖼️ ",
    "END_SESSION_TRIGGER_IMAGE_ES": "IMAGEN INDICADORA DE FIN DE SESIÓN 🖼️ ",
    "LIST_TRIGGER_IMAGES_ES": "IMÁGENES DE LOS INDICADORES DE CAPTURA 🖼️ ",
    "HSV_COLOR_AREA_ES": "COLOR DE LAS ÁREAS 🟢 ",
    "INTEREST_TRIGGER_AREA_ES": "ÁREA DE LAS IMÁGENES INDICADORAS 🔲 ",
    "COMPARISON_AREA_ES": "ÁREA DE COMPARACIÓN 🔲 ",
    #WEB
    "SCREEN_RECORDING_ES": "VIDEO DE LA GRABACIÓN DE PANTALLA 📹 ",
    "CAPTURES_ES": "SESIÓN DE CAPTURAS 📸 ",
    #VIDEO
    "VIDEO_SOURCE_ES": "VÍDEO DE ORIGEN 🎞️ ",
}

dict_panel_title_pt = {
    "PROJECT_PT": "PROJETO GERAL 🗃️ ",
    "START_SESSION_TRIGGER_IMAGE_PT": "IMAGEM INDICADORA DE INÍCIO DE SESSÃO 🖼️ ",
    "END_SESSION_TRIGGER_IMAGE_PT": "IMAGEM INDICADORA DE FIM DE SESSÃO 🖼️ ",
    "LIST_TRIGGER_IMAGES_PT": "IMAGENS DOS INDICADORES DE CAPTURA 🖼️ ",
    "HSV_COLOR_AREA_PT": "COR DAS ÁREAS 🟢 ",
    "INTEREST_TRIGGER_AREA_PT": "ÁREA DAS IMAGENS INDICADORAS 🔲 ",
    "COMPARISON_AREA_PT": "ÁREA DE COMPARAÇÃO 🔲 ",
    #WEB
    "SCREEN_RECORDING_PT": "GRAVAÇÃO DE TELA EM VÍDEO 📹 ",
    "CAPTURES_PT": "SESSÃO DE CAPTURAS 📸 ",
    #VIDEO
    "VIDEO_SOURCE_PT": "VÍDEO DE ORIGEM 🎞️ ",
}



dict_menu_panel_en ={    
    "AUTOMATIC_OPTION_EN": "SELECT AN AUTOMATIC OPTION 🕹️",
    "RELOAD_CONFIG_EN": "RELOAD SETTINGS 🔄",
    "PROJECT_EN": "START MENU 🏁",
    "START_SESSION_TRIGGER_IMAGE_EN": "MENU - START IMAGE SESSION INDICATOR 🖼️",
    "END_SESSION_TRIGGER_IMAGE_EN": "MENU - END IMAGE SESSION INDICATOR 🖼️",
    "LIST_TRIGGER_IMAGES_EN": "MENU - IMAGES OF CAPTURE INDICATORS 🖼️",
    "HSV_COLOR_AREA_EN": "MENU - COLOR OF AREAS 🟢",
    "INTEREST_TRIGGER_AREA_EN": "MENU - AREA OF INDICATORS IMAGES 🔲",
    "COMPARISON_AREA_EN": "MENU - AREA OF COMPARISON 🔲 ",
    "MENU_SCREEN_SESSION_EN": "NEW CAPTURE SESSION 🗂️",
    "INIT_MAIN_PROCESS_EN": "START CAPTURE PROCESS 📸",
    #VIDEO
    "VIDEO_SOURCE_EN": "MENU - VIDEO SOURCE 🎞️",
     #WEB
    "SCREEN_RECORDING_EN": "MENU - VIDEO SCREEN RECORDING 📹",
}

dict_menu_panel_es ={ 
    "AUTOMATIC_OPTION_ES": "SELECCIONAR UNA OPCIÓN AUTOMÁTICA 🕹️",
    "RELOAD_CONFIG_ES": "RECARGAR CONFIGURACIÓN 🔄",
    "PROJECT_ES": "MENÚ DE INICIO 🏁",
    "START_SESSION_TRIGGER_IMAGE_ES": "MENÚ DE INICIO DE SESIÓN DE IMAGEN 🖼️",
    "END_SESSION_TRIGGER_IMAGE_ES": "MENÚ DE FIN DE SESIÓN DE IMAGEN 🖼️",
    "LIST_TRIGGER_IMAGES_ES": "MENÚ DE IMÁGENES INDICADORAS DE CAPTURA 🖼️",
    "HSV_COLOR_AREA_ES": "MENÚ COLOR DE LAS ÁREAS 🟢",
    "INTEREST_TRIGGER_AREA_ES": "MENÚ DE ÁREA DE IMÁGENES INDICADORAS 🔲",
    "COMPARISON_AREA_ES": "MENÚ DE ÁREA DE COMPARACIÓN 🔲",
    "MENU_SCREEN_SESSION_ES": "NUEVA SESSION DE CAPTURAS 🗂️",
    "INIT_MAIN_PROCESS_ES": "INICIAR EL PROCESO DE CAPTURAS 📸",
    #VIDEO
    "VIDEO_SOURCE_ES": "MENÚ VIDEO DE ORIGEN 🎞️",
     #WEB
    "SCREEN_RECORDING_ES": "MENÚ DE GRABACIÓN DE PANTALLA 📹",
   
}

dict_menu_panel_pt ={    
    "AUTOMATIC_OPTION_PT": "SELECIONE UMA OPÇÃO AUTOMÁTICA 🕹️" ,
    "RELOAD_CONFIG_PT": "RECARREGAR CONFIGURAÇÕES 🔄",
    "PROJECT_PT": "MENU DE INÍCIO 🏁",
    "START_SESSION_TRIGGER_IMAGE_PT": "MENU DE INÍCIO DE SESSÃO DE IMAGEM 🖼️",
    "END_SESSION_TRIGGER_IMAGE_PT": "MENU DE FIM DE SESSÃO DE IMAGEM 🖼️",
    "LIST_TRIGGER_IMAGES_PT": "MENU DE IMAGENS DOS INDICADORES DE CAPTURA 🖼️",
    "HSV_COLOR_AREA_PT": "MENU COR DAS ÁREAS 🟢",
    "INTEREST_TRIGGER_AREA_PT": "MENU DE ÁREA DAS IMAGENS INDICADORAS 🔲",
    "COMPARISON_AREA_PT": "MENU DE ÁREA DE COMPARAÇÃO 🔲",
    "MENU_SCREEN_SESSION_PT": "NOVA SESSÃO DE CAPTURAS 🗂️",
    "INIT_MAIN_PROCESS_PT": "INICIAR O PROCESSO DE CAPTURAS 📸",
    #VIDEO
    "VIDEO_SOURCE_PT": "MENU DE GRAVAÇÃO DE TELA EM VÍDEO 🎞️",
     #WEB
    "SCREEN_RECORDING_PT": "MENU DE GRAVAÇÃO DE TELA EM VÍDEO 📹",

}


dict_menu_panel = {
    **dict_menu_panel_en, 
    **dict_menu_panel_es,
    **dict_menu_panel_pt,
}


dict_panel_title = { 
    **dict_panel_title_en,
    **dict_panel_title_es,
    **dict_panel_title_pt,
}
