
from base_class.link_keys import Link
from base_class.os_env_processor_folders import EnvFolders


link_image_areas_listed = Link.create_link_key(type=Link.LINK_IMAGE_SETTING, folder=EnvFolders.AREAS_IMAGE_OCR_LISTED)
lin_folder_captures = Link.create_link_key(type=Link.LINK_FOLDER, folder=EnvFolders.CAPTURES)
lin_folder_test = Link.create_link_key(type=Link.LINK_FOLDER, folder=EnvFolders.IMAGES_SETTING_TESTING)
lin_folder_area_ocr = Link.create_link_key(type=Link.LINK_FOLDER, folder=EnvFolders.AREAS_IMAGE_OCR)
hsv_color_folder = Link.create_link_key(type=Link.LINK_FOLDER, folder=EnvFolders.HSV_COLOR_AREA)
help_areas_ocr = {
    "step_0_title_ES": "Selecciona una imagen de las capturas generadas por el módulo 'Image Collector'",
    "step_0_title_EN": "Select an image from the captures generated by the 'Image Collector' module",
    "step_0_title_PT": "Selecione uma imagem das capturas geradas pelo módulo 'Image Collector'",
    
    "step_0_description_ES": f"Copia y pega manualmente una imagen de las capturas en la carpeta {lin_folder_area_ocr}",
    "step_0_description_EN": f"Manually copy and paste an image from the captures into the folder {lin_folder_area_ocr}",
    "step_0_description_PT": f"Copie e cole manualmente uma imagem das capturas na pasta {lin_folder_area_ocr}",
    
    "step_1_title_ES": "Indica las áreas de extracción de texto",
    "step_1_title_EN": "Indicate the text extraction areas",
    "step_1_title_PT": "Indique as áreas de extração de texto",
    
    "step_1_description_ES": f"Con un editor de imágenes sencillo, selecciona las áreas dibujando rectángulos alrededor de ellas. Utiliza el color de la imagen en la carpeta  {hsv_color_folder}",
    "step_1_description_EN": f"Using a simple image editor, select the areas by drawing rectangles around them. Use the color from the image in the {hsv_color_folder}",
    "step_1_description_PT": f"Usando um editor de imagens simples, selecione as áreas desenhando retângulos ao redor delas. Utilize a cor da imagem na pasta  {hsv_color_folder}",
}


help_main_area_menu = {
    
    "step_0_title_ES": "Configuración de Reconocimiento de Caracteres y Obtención de Valores",
    "step_0_title_EN": "Character Recognition and Value Extraction Settings",
    "step_0_title_PT": "Configuração de Reconhecimento de Caracteres e Extração de Valores",
    
    "step_0_description_ES": "Este menú te permite configurar el proceso de reconocimiento de caracteres y la obtención de valores para cada área específica de la imagen. Puedes ajustar las configuraciones individualmente para cada área que hayas seleccionado previamente. Las opciones incluyen la personalización del reconocimiento de texto, la definición de valores finales y la organización de áreas en grupos para una mejor gestión.",
    "step_0_description_EN": "This menu allows you to configure character recognition and value extraction for each specific area of the image. You can adjust settings individually for each previously selected area. Options include customizing text recognition, defining final values, and organizing areas into groups for better management.",
    "step_0_description_PT": "Este menu permite configurar o reconhecimento de caracteres e a extração de valores para cada área específica da imagem. Você pode ajustar as configurações individualmente para cada área selecionada anteriormente. As opções incluem personalizar o reconhecimento de texto, definir valores finais e organizar áreas em grupos para uma melhor gestão.",
    
    "step_1_title_ES": "Etiquetado y Obtención del Valor Final",
    "step_1_title_EN": "Labeling and Final Value Extraction",
    "step_1_title_PT": "Rotulagem e Extração do Valor Final",
    
    "step_1_description_ES": "En esta etapa, puedes asignar un nombre que represente el valor final que quieres extraer de cada área de la imagen. También podrás definir el tipo de dato que mejor se adapte a tus necesidades, como texto, número o fecha. Adicionalmente, tendrás la opción de seleccionar una porción específica del texto reconocido, permitiéndote enfocar solo en la parte relevante de la cadena original.",
    "step_1_description_EN": "In this step, you can assign a name to represent the final value you want to extract from each area of the image. You can also define the data type that best suits your needs, such as text, number, or date. Additionally, you will have the option to select a specific portion of the recognized text, allowing you to focus only on the relevant part of the original string.",
    "step_1_description_PT": "Nesta etapa, você pode atribuir um nome para representar o valor final que deseja extrair de cada área da imagem. Você também pode definir o tipo de dado que melhor se adapta às suas necessidades, como texto, número ou data. Além disso, você terá a opção de selecionar uma parte específica do texto reconhecido, permitindo que você se concentre apenas na parte relevante da string original.",

    "step_2_title_ES": "Imagen con las Áreas Enumeradas",
    "step_2_title_EN": "Image with Enumerated Areas",
    "step_2_title_PT": "Imagem com Áreas Enumeradas",
    
    "step_2_description_ES": f"{link_image_areas_listed}",
    "step_2_description_EN": f"{link_image_areas_listed}",
    "step_2_description_PT": f"{link_image_areas_listed}",
}


help_test_area = {
    "step_0_title_ES": "Carpeta de Capturas",
    "step_0_title_EN": "ScreenShots Folder",
    "step_0_title_PT": "Pasta de Capturas de Tela",
    
    "step_0_description_ES": f"{lin_folder_captures}",
    "step_0_description_EN": f"{lin_folder_captures}",
    "step_0_description_PT": f"{lin_folder_captures}",
    
    "step_1_title_ES": "Carpeta Test de Capturas",
    "step_1_title_EN": "ScreenShots Test Folder",
    "step_1_title_PT": "Pasta Test Capturas de Tela",
    
    "step_1_description_ES": f"{lin_folder_test}",
    "step_1_description_EN": f"{lin_folder_test}",
    "step_1_description_PT": f"{lin_folder_test}",
}

if __name__ == "__main__":
    print(link_image_areas_listed)
    print(lin_folder_captures)
    print(lin_folder_test)



