from enum import Enum

class ConfigMenuProject(Enum):
    AUTOMATIC_OPTION = "AUTOMATIC_OPTION"
    RELOAD_CONFIG = "RELOAD_CONFIG"
    WELCOME = "WELCOME"
    AREAS_IMAGE_OCR = "AREAS_IMAGE_OCR"
    SETTING_AREAS_OCR = "SETTING_AREAS_OCR"
    INIT_OCR_PROCESS = "INIT_OCR_PROCESS"
    MENU_DATA_PROCESS = "MENU_DATA_PROCESS"
    ACTIVATE_GPU = "ACTIVATE_GPU"
    EXIT = "EXIT"
