from enum import Enum

class ConfigSections(Enum):
    PROJECT = "PROJECT"
    HSV_COLOR_AREA = "HSV_COLOR_AREA"
    AREAS_IMAGE_OCR = "AREAS_IMAGE_OCR"
    AREAS_IMAGE_OCR_LISTED = "AREAS_IMAGE_OCR_LISTED"
    SUB_IMAGE_TO_REMOVE = "SUB_IMAGE_TO_REMOVE"
    SECTION_SETTING_AREAS_OCR = "SETTING_AREAS_OCR"
    PROJECT_SESSION_STATE = "PROJECT_SESSION_STATE"
    TASK_IN_PROGRESS = "TASK_IN_PROGRESS"

class AreaSectionsPrefix(Enum):
    SECTION_AREA_PREFIX = "AREA_"

