from enum import Enum


class ConfigSections(Enum):
    PROJECT = "PROJECT"
    SCREEN_RECORDING = "SCREEN_RECORDING"
    VIDEO_SOURCE = "VIDEO_SOURCE"
    START_SESSION_TRIGGER_IMAGE = "START_SESSION_TRIGGER_IMAGE"
    END_SESSION_TRIGGER_IMAGE = "END_SESSION_TRIGGER_IMAGE"
    LIST_TRIGGER_IMAGES = "LIST_TRIGGER_IMAGES"
    INTEREST_TRIGGER_AREA = "INTEREST_TRIGGER_AREA"
    COMPARISON_AREA = "COMPARISON_AREA"
    HSV_COLOR_AREA = "HSV_COLOR_AREA"
    CAPTURES = "CAPTURES"
